# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 650)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget#canshu{border: 2px solid rgba(0,0,0,0.5);\n"
"border-radius: 10px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.canshu = QtWidgets.QWidget(self.centralwidget)
        self.canshu.setGeometry(QtCore.QRect(10, 20, 691, 171))
        self.canshu.setAutoFillBackground(False)
        self.canshu.setStyleSheet("QWidget#canshu{border: 2px solid rgba(0,0,0,0.5); \n"
"border-radius: 10px;}")
        self.canshu.setObjectName("canshu")
        self.gridLayout = QtWidgets.QGridLayout(self.canshu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pondA_layout = QtWidgets.QGridLayout()
        self.pondA_layout.setObjectName("pondA_layout")
        self.label_2 = QtWidgets.QLabel(self.canshu)
        self.label_2.setMinimumSize(QtCore.QSize(100, 20))
        self.label_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pondA_layout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.canshu)
        self.label_3.setMinimumSize(QtCore.QSize(10, 10))
        self.label_3.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pondA_layout.addWidget(self.label_3, 1, 0, 1, 1)
        self.pump_rate_A = QtWidgets.QLineEdit(self.canshu)
        self.pump_rate_A.setMinimumSize(QtCore.QSize(100, 20))
        self.pump_rate_A.setMaximumSize(QtCore.QSize(200, 40))
        self.pump_rate_A.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pump_rate_A.setObjectName("pump_rate_A")
        self.pondA_layout.addWidget(self.pump_rate_A, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.canshu)
        self.label_4.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.pondA_layout.addWidget(self.label_4, 2, 0, 1, 1)
        self.maxvolume_A = QtWidgets.QLineEdit(self.canshu)
        self.maxvolume_A.setMinimumSize(QtCore.QSize(100, 20))
        self.maxvolume_A.setMaximumSize(QtCore.QSize(200, 16777215))
        self.maxvolume_A.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.maxvolume_A.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.maxvolume_A.setObjectName("maxvolume_A")
        self.pondA_layout.addWidget(self.maxvolume_A, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.pondA_layout, 1, 0, 1, 1)
        self.islinkcheackbox = QtWidgets.QCheckBox(self.canshu)
        self.islinkcheackbox.setObjectName("islinkcheackbox")
        self.gridLayout.addWidget(self.islinkcheackbox, 3, 0, 1, 1)
        self.simulatebtn = QtWidgets.QPushButton(self.canshu)
        self.simulatebtn.setMinimumSize(QtCore.QSize(80, 20))
        self.simulatebtn.setMaximumSize(QtCore.QSize(100, 40))
        self.simulatebtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.simulatebtn.setCheckable(False)
        self.simulatebtn.setObjectName("simulatebtn")
        self.gridLayout.addWidget(self.simulatebtn, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.canshu)
        self.label.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pondB_layout = QtWidgets.QGridLayout()
        self.pondB_layout.setObjectName("pondB_layout")
        self.label_5 = QtWidgets.QLabel(self.canshu)
        self.label_5.setMinimumSize(QtCore.QSize(100, 20))
        self.label_5.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.pondB_layout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.canshu)
        self.label_6.setMinimumSize(QtCore.QSize(10, 10))
        self.label_6.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.pondB_layout.addWidget(self.label_6, 1, 0, 1, 1)
        self.pump_rate_B = QtWidgets.QLineEdit(self.canshu)
        self.pump_rate_B.setMinimumSize(QtCore.QSize(100, 20))
        self.pump_rate_B.setMaximumSize(QtCore.QSize(200, 40))
        self.pump_rate_B.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.pump_rate_B.setObjectName("pump_rate_B")
        self.pondB_layout.addWidget(self.pump_rate_B, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.canshu)
        self.label_7.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.pondB_layout.addWidget(self.label_7, 2, 0, 1, 1)
        self.maxvolume_B = QtWidgets.QLineEdit(self.canshu)
        self.maxvolume_B.setMinimumSize(QtCore.QSize(100, 20))
        self.maxvolume_B.setMaximumSize(QtCore.QSize(200, 16777215))
        self.maxvolume_B.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.maxvolume_B.setObjectName("maxvolume_B")
        self.pondB_layout.addWidget(self.maxvolume_B, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.pondB_layout, 1, 1, 1, 1)
        self.output_view = QtWidgets.QWidget(self.centralwidget)
        self.output_view.setGeometry(QtCore.QRect(10, 220, 691, 401))
        self.output_view.setObjectName("output_view")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.output_view)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.output_view)
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.stackedWidget = QtWidgets.QStackedWidget(self.output_view)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_welcome = QtWidgets.QWidget()
        self.page_welcome.setObjectName("page_welcome")
        self.widget = QtWidgets.QWidget(self.page_welcome)
        self.widget.setGeometry(QtCore.QRect(20, 20, 631, 311))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(60, 20))
        self.label_9.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.run_progress_bar = QtWidgets.QProgressBar(self.widget)
        self.run_progress_bar.setMinimumSize(QtCore.QSize(200, 30))
        self.run_progress_bar.setMaximumSize(QtCore.QSize(1000, 40))
        self.run_progress_bar.setProperty("value", 24)
        self.run_progress_bar.setObjectName("run_progress_bar")
        self.horizontalLayout.addWidget(self.run_progress_bar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.stackedWidget.addWidget(self.page_welcome)
        self.page_result = QtWidgets.QWidget()
        self.page_result.setObjectName("page_result")
        self.draw_selection_box = QtWidgets.QComboBox(self.page_result)
        self.draw_selection_box.setGeometry(QtCore.QRect(21, 11, 150, 20))
        self.draw_selection_box.setMinimumSize(QtCore.QSize(150, 20))
        self.draw_selection_box.setMaximumSize(QtCore.QSize(250, 40))
        self.draw_selection_box.setObjectName("draw_selection_box")
        self.draw_selection_box.addItem("")
        self.draw_selection_box.addItem("")
        self.draw_selection_box.addItem("")
        self.draw_selection_box.addItem("")
        self.draw_selection_box.addItem("")
        self.draw_widget = MatplotlibWidget(self.page_result)
        self.draw_widget.setGeometry(QtCore.QRect(20, 40, 651, 291))
        self.draw_widget.setObjectName("draw_widget")
        self.stackedWidget.addWidget(self.page_result)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.draw_widget2 = MatplotlibWidget(self.page)
        self.draw_widget2.setGeometry(QtCore.QRect(10, 10, 661, 321))
        self.draw_widget2.setObjectName("draw_widget2")
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.testbtn1 = QtWidgets.QPushButton(self.output_view)
        self.testbtn1.setObjectName("testbtn1")
        self.horizontalLayout_2.addWidget(self.testbtn1)
        self.testbtn2 = QtWidgets.QPushButton(self.output_view)
        self.testbtn2.setMinimumSize(QtCore.QSize(100, 20))
        self.testbtn2.setObjectName("testbtn2")
        self.horizontalLayout_2.addWidget(self.testbtn2)
        self.testbtn3 = QtWidgets.QPushButton(self.output_view)
        self.testbtn3.setObjectName("testbtn3")
        self.horizontalLayout_2.addWidget(self.testbtn3)
        self.testbtn4 = QtWidgets.QPushButton(self.output_view)
        self.testbtn4.setMinimumSize(QtCore.QSize(120, 20))
        self.testbtn4.setObjectName("testbtn4")
        self.horizontalLayout_2.addWidget(self.testbtn4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pump_rate_A.raise_()
        self.label_4.raise_()
        self.maxvolume_A.raise_()
        self.islinkcheackbox.raise_()
        self.simulatebtn.raise_()
        self.label_8.raise_()
        self.stackedWidget.raise_()
        self.testbtn1.raise_()
        self.testbtn2.raise_()
        self.testbtn3.raise_()
        self.testbtn4.raise_()
        self.output_view.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "调蓄带A"))
        self.label_3.setText(_translate("MainWindow", "水泵流量"))
        self.pump_rate_A.setPlaceholderText(_translate("MainWindow", "单位：m3/s"))
        self.label_4.setText(_translate("MainWindow", "库容"))
        self.maxvolume_A.setPlaceholderText(_translate("MainWindow", "单位：m3"))
        self.islinkcheackbox.setText(_translate("MainWindow", "是否连通"))
        self.simulatebtn.setText(_translate("MainWindow", "运行模拟"))
        self.label.setText(_translate("MainWindow", "参数设置"))
        self.label_5.setText(_translate("MainWindow", "调蓄带B"))
        self.label_6.setText(_translate("MainWindow", "水泵流量"))
        self.pump_rate_B.setPlaceholderText(_translate("MainWindow", "单位：m3/s"))
        self.label_7.setText(_translate("MainWindow", "库容"))
        self.maxvolume_B.setPlaceholderText(_translate("MainWindow", "单位：m3"))
        self.label_8.setText(_translate("MainWindow", "计算结果"))
        self.label_9.setText(_translate("MainWindow", "模拟进度"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "程序说明：\n"
"该程序用于计算调蓄带在不同条件下灌溉排水，超量排水以及水泵运行时间的时间序列并作图显示；结果文件输出按钮用于输出上述时间序列的数据，进行保存。若相关调蓄带参数未进行设置，将采用初始默认值（题目中的设定）或上一次的设置来进行模拟。\n"
"同时，此窗口还用来显示一些程序运行信息，便于debug."))
        self.draw_selection_box.setItemText(0, _translate("MainWindow", "总水量时间序列图"))
        self.draw_selection_box.setItemText(1, _translate("MainWindow", "灌溉排水时间序列图"))
        self.draw_selection_box.setItemText(2, _translate("MainWindow", "超量排水时间序列图"))
        self.draw_selection_box.setItemText(3, _translate("MainWindow", "雨污水汇入时间序列图"))
        self.draw_selection_box.setItemText(4, _translate("MainWindow", "水泵运行时间图"))
        self.testbtn1.setText(_translate("MainWindow", "程序模拟状态"))
        self.testbtn2.setText(_translate("MainWindow", "各种时间序列图"))
        self.testbtn3.setText(_translate("MainWindow", "利用效益图"))
        self.testbtn4.setText(_translate("MainWindow", "结果文件输出"))
from MatplotlibWidget import MatplotlibWidget
